services:
  app:
    image: ghcr.io/maximilianhagerf/hagerf-cv:latest
    ports:
      - "3000:3000"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
