/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthCallbackImport } from './routes/auth.callback'
import { Route as ShareTokenImport } from './routes/share.$token'
import { Route as AuthedContentImport } from './routes/_authed.content'
import { Route as AuthedDashboardImport } from './routes/_authed.dashboard'
import { Route as AuthedProfileImport } from './routes/_authed.profile'
import { Route as AuthedCvIdImport } from './routes/_authed.cv.$id'
import { Route as AuthedCvIdPreviewImport } from './routes/_authed.cv.$id.preview'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

const ShareTokenRoute = ShareTokenImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthedContentRoute = AuthedContentImport.update({
  id: '/_authed/content',
  path: '/content',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/_authed/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedProfileRoute = AuthedProfileImport.update({
  id: '/_authed/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCvIdRoute = AuthedCvIdImport.update({
  id: '/_authed/cv/$id',
  path: '/cv/$id',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCvIdPreviewRoute = AuthedCvIdPreviewImport.update({
  id: '/_authed/cv/$id/preview',
  path: '/cv/$id/preview',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: '/_authed'
      fullPath: '/_authed'
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenImport
      parentRoute: typeof rootRoute
    }
    '/_authed/content': {
      id: '/_authed/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthedContentImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cv/$id': {
      id: '/_authed/cv/$id'
      path: '/cv/$id'
      fullPath: '/cv/$id'
      preLoaderRoute: typeof AuthedCvIdImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/cv/$id/preview': {
      id: '/_authed/cv/$id/preview'
      path: '/cv/$id/preview'
      fullPath: '/cv/$id/preview'
      preLoaderRoute: typeof AuthedCvIdPreviewImport
      parentRoute: typeof AuthedRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/content': typeof AuthedContentRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/cv/$id': typeof AuthedCvIdRoute
  '/cv/$id/preview': typeof AuthedCvIdPreviewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/content': typeof AuthedContentRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/cv/$id': typeof AuthedCvIdRoute
  '/cv/$id/preview': typeof AuthedCvIdPreviewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authed/content': typeof AuthedContentRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/cv/$id': typeof AuthedCvIdRoute
  '/_authed/cv/$id/preview': typeof AuthedCvIdPreviewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/callback' | '/share/$token' | '/content' | '/dashboard' | '/profile' | '/cv/$id' | '/cv/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/callback' | '/share/$token' | '/content' | '/dashboard' | '/profile' | '/cv/$id' | '/cv/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth/callback'
    | '/share/$token'
    | '/_authed/content'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/cv/$id'
    | '/_authed/cv/$id/preview'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

export interface AuthedRouteChildren {
  AuthedContentRoute: typeof AuthedContentRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedCvIdRoute: typeof AuthedCvIdRoute
  AuthedCvIdPreviewRoute: typeof AuthedCvIdPreviewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ShareTokenRoute: ShareTokenRoute,
}

const authedRouteChildren: AuthedRouteChildren = {
  AuthedContentRoute: AuthedContentRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedCvIdRoute: AuthedCvIdRoute,
  AuthedCvIdPreviewRoute: AuthedCvIdPreviewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

// Also register children on the authed layout route
;(AuthedRoute as any)._addFileChildren(authedRouteChildren)

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/auth/callback",
        "/share/$token"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/content",
        "/_authed/dashboard",
        "/_authed/profile",
        "/_authed/cv/$id",
        "/_authed/cv/$id/preview"
      ]
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    },
    "/share/$token": {
      "filePath": "share.$token.tsx"
    },
    "/_authed/content": {
      "filePath": "_authed.content.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed.dashboard.tsx"
    },
    "/_authed/profile": {
      "filePath": "_authed.profile.tsx"
    },
    "/_authed/cv/$id": {
      "filePath": "_authed.cv.$id.tsx"
    },
    "/_authed/cv/$id/preview": {
      "filePath": "_authed.cv.$id.preview.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
